### ISSUE TITLE
ESMAR manuscript

### ISSUE THREAD

**Issue by softloud** [softloud/nmareporting#7]
Hi @DrMattG, 

Still filling in a few blanks on the [manuscript](https://github.com/softloud/nmareporting/blob/master/manuscript/draft/nmarep-ms.pdf), and then I know I'll be able to smash out the presentation for this. 

But now I've got a task for you. 

- [x] Try contribution workflow: create an eco vignette.

![image](https://user-images.githubusercontent.com/13408706/105139514-84e15700-5b4a-11eb-8196-07c2180cabe5.png)

**Comment by DrMattG** [comment]
pull request #9

**Comment by softloud** [comment]
# notes from Monday 2021-01-25 

meeting with @EBX-meta

2nd draft structure 

# intro

Survey current reporting standards (#1) 
Focus on nma in medicine

# case study

[nmareporting](https://github.com/softloud/nmareporting) reporting standards in network meta-analysis in medicine according to Cochrane's reporting standards 

# discussion

Principled evidence synthesis 
Opinionated automated reports (consult with @wviechtb after second draft, if he has time/interest)

**Comment by softloud** [comment]
on second thought, should migrate to a new issue #10  now that the ESMAR draft is done
